tags_pixabay = ['act', 'action', 'african american', 'african american woman', 'alone', 'anatomy', 'angel', 'art', 'ass',
                'attractive', 'autumn', 'back', 'bath', 'bdsm', 'beach', 'beautiful', 'beautiful woman', 'beauty', 'bed',
                'bella', 'bikini', 'black', 'black dress', 'black white', 'black woman', 'black-and-white', 'blond', 'blonde',
                'blue', 'body', 'boots', 'boudoir', 'bra', 'breast', 'brunette', 'butt', 'car wash', 'charm', 'chill',
                'chopper', 'classic', 'clean', 'clothes', 'club', 'colors', 'cosmetics', 'costume', 'costumes', 'countrygirl',
                'couple', 'creative', 'dance', 'dancer', 'dancing', 'dark', 'dice', 'draw', 'drawing', 'dream', 'dress',
                'erotic', 'erotica', 'eroticism', 'exhibition', 'exotic', 'face', 'fantasy', 'fashion', 'fashion girl',
                'fashionable girl', 'feminine', 'fence', 'fiction', 'fighter', 'fitness', 'girl', 'girl at the computer',
                'girl in overalls', 'girl in the forest', 'girl in white dress', 'girl lying on the grass',
                'girl washes the car', 'girls', 'glamour', 'glasses', 'goldsmith', 'good', 'greece', 'happy', 'hat', 'hot',
                'in a shirt', 'indonesia', 'indoor', 'interior', 'island', 'kiss', 'leg', 'legs', 'lick', 'lies', 'light',
                'lingerie', 'lips', 'listening to music', 'long', 'looking up', 'love', 'lovely', 'make up', 'make-up',
                'makeup', 'marilyn monroe', 'mirror', 'miss', 'model', 'modeling', 'modelling', 'monochrome', 'mood', 'morning',
                'muscles', 'mystery', 'naked', 'nature', 'nice', 'night', 'nightie', 'nipple', 'nude', 'ocean', 'one',
                'outdoor', 'outdoors', 'pin-up girls', 'pinky', 'pole dance', 'pole dancer', 'pool', 'popa', 'porch', 'pose',
                'pretty', 'red', 'reflection', 'retouch', 'romantic', 'ropes', 'roses', 'science fiction', 'sea',
                'secretary', 'sensual', 'sensuality', 'sexuality', 'sexy', 'sexy athlete', 'sexy girl', 'short dress', 'shout',
                'shower', 'sitting', 'six pack abs', 'skin', 'skirt', 'sleeping', 'slender', 'slimming', 'smile', 'smiling',
                'sofa', 'sport', 'sports', 'sportswear', 'summer', 'sun', 'sun-bathing', 'sunglasses', 'sunlight', 'sunset',
                'surf', 'surfboard', 'surfer', 'swim', 'swimsuit', 'tanga', 'tattoo', 'teeth', 'that',
                'the girl in the elevator', 'the woods', 'thong', 'thoughtful', 'twins', 'two', 'underwater', 'underwear',
                'used', 'very beautiful', 'vintage', 'water', 'wave', 'welfare', 'wet', 'wind', 'woke up', 'woman', 'women',
                'womens day', 'woods', 'workout', 'yoga', 'young', 'young girl', 'young model', 'young woman', 'young women']
